

void main(List<String> arguments) {
try {
  int result= 10~/0;
  print("result $result");
} catch (e) {
 
  print("An exception occurred: $e");
} finally {
 
}

}
